/**
 * Antiques catalog — source of truth for /heritage.
 * Images live in `public/images/heritage/` (local paths only).
 */

export type HeritageItem = {
  id: string
  title: string
  description: string
  era: string
  origin: string
  category: string
  image: string
  imageAlt: string
}

const img = (file: string) => `/images/heritage/${file}`

export const heritageCategories = [
  "Antique Coins",
  "Rare Currency",
  "Heritage Objects",
  "Rare Memorabilia",
  "Vintage Instruments",
  "Timepieces",
  "Ceremonial Arms",
  "Illumination",
  "Jewelry & Adornment",
  "Decorative Arts",
] as const

export const heritageCategoryCopy: Record<string, string> = {
  "Antique Coins":
    "Medallic gold and commemorative issues — portraiture, allegory, and mint-grade relief.",
  "Rare Currency":
    "Symbolic and ceremonial tender preserved as objects of design and history.",
  "Heritage Objects":
    "Vessels, instruments, and campaign pieces elevated by material and craft.",
  "Rare Memorabilia":
    "Crowns, shields, and courtly artifacts held for lineage and form.",
  "Vintage Instruments":
    "Gramophones, radios, optics, and sound machines of the mechanical age.",
  Timepieces: "Pocket, wrist, and architectural clocks — openwork, skeleton, and celestial dials.",
  "Ceremonial Arms":
    "Blades, scabbards, and heraldic defense pieces with ornamental metallurgy.",
  Illumination: "Lamps and lanterns in brass, glass, and pierced metal for domestic and ritual light.",
  "Jewelry & Adornment":
    "Pendants, collars, and gem settings from Egyptian revival to modern atelier work.",
  "Decorative Arts":
    "Frames, furniture strongboxes, and wall assemblages of gilded ornament.",
}

export const heritageHero = {
  eyebrow: "Collection · Antiques",
  headline: "Provenance. Craft. Continuity.",
  subheading:
    "A carefully held collection of rare antiques, ceremonial objects, and heritage instruments — presented with institutional clarity.",
  image: img("gramophone-classic.webp"),
  imageAlt: "Mahogany and brass antique gramophone with flared horn",
}

/** Primary gallery — one entry per distinct work (alts remain on disk for later use). */
export const heritageItems: HeritageItem[] = [
  {
    id: "hc-gramophone",
    title: "Salon Gramophone",
    description:
      "Mahogany cabinet with brass tone-arm and flared acoustic horn — a centerpiece of early recorded sound.",
    era: "c. 1910–1925",
    origin: "Europe",
    category: "Vintage Instruments",
    image: img("gramophone-classic.webp"),
    imageAlt: "Antique gramophone with golden horn in a wood-paneled room",
  },
  {
    id: "hc-gramophone-gilt",
    title: "Gilt Horn Phonograph",
    description: "Fully gilded horn and base with ornate columns — display-grade acoustic machine.",
    era: "c. 1920s",
    origin: "Continental Europe",
    category: "Vintage Instruments",
    image: img("6f9366f9-b37e-4a40-b1fb-477ee756fef1.webp"),
    imageAlt: "All-gold ornamental gramophone on a wooden table",
  },
  {
    id: "hc-cabinet-radio",
    title: "Cabinet Receiver Ensemble",
    description:
      "Wooden radio cabinet with exposed brass rotor, desk globe, and listening set — a study in early broadcast furniture.",
    era: "c. 1930s",
    origin: "Western Europe",
    category: "Vintage Instruments",
    image: img("02ef0516-d52f-4bcb-8107-d057943f8f7a.webp"),
    imageAlt: "Vintage wooden radio cabinet with globe and headphones",
  },
  {
    id: "hc-chrono-clock",
    title: "Field Chronograph Cabinet",
    description:
      "Brass multi-dial time engine with luminous turquoise center — steampunk precision as sculpture.",
    era: "Studio contemporary · period form",
    origin: "Workshop collection",
    category: "Timepieces",
    image: img("03aaf4a4-b973-4399-8e0e-e5ed3c0dbf5e.webp"),
    imageAlt: "Ornate brass multi-dial clock on a desert table",
  },
  {
    id: "hc-skeleton-watch",
    title: "Skeleton Wrist Chronometer",
    description: "Gold case, Roman chapter ring, and open gear train on a crocodile strap.",
    era: "Contemporary atelier",
    origin: "Switzerland-inspired",
    category: "Timepieces",
    image: img("849cc3fb-30de-4092-b2c3-3264786aefd3.webp"),
    imageAlt: "Gold skeleton watch with leather strap",
  },
  {
    id: "hc-pocket-celestial",
    title: "Celestial Hunter Pocket Watch",
    description: "Hunter case with dual dials — constellation night face and open-heart day plate.",
    era: "c. 1890–1910 form",
    origin: "Switzerland",
    category: "Timepieces",
    image: img("b0fe1b38-a22a-447e-a7b8-632089c570eb.webp"),
    imageAlt: "Open gold pocket watch with blue celestial dial",
  },
  {
    id: "hc-framed-mechanisms",
    title: "Four Framed Mechanisms",
    description: "Gilded frames holding kinetic brass assemblages — clockwork as wall composition.",
    era: "Contemporary art object",
    origin: "Studio collection",
    category: "Decorative Arts",
    image: img("14036f10-462c-46b7-b4b0-a9ae2ec81862.webp"),
    imageAlt: "Four ornate framed clockwork assemblies",
  },
  {
    id: "hc-goggles",
    title: "Aviator Brass Goggles",
    description: "Leather and brass flight goggles with green lenses and precision hardware.",
    era: "c. 1915–1930 form",
    origin: "Britain / France",
    category: "Heritage Objects",
    image: img("goggles-steampunk-green.webp"),
    imageAlt: "Steampunk brass goggles with green glass",
  },
  {
    id: "hc-bull-mask",
    title: "Bull-Horn Viewing Mask",
    description: "Ceremonial leather and brass mask with green lenses and golden horns.",
    era: "Studio contemporary",
    origin: "Workshop collection",
    category: "Rare Memorabilia",
    image: img("4474ea78-e1c2-45fb-a14a-dde481c932d0.webp"),
    imageAlt: "Steampunk bull-horn goggle mask",
  },
  {
    id: "hc-telescope",
    title: "Survey Telescope on Mount",
    description: "Crimson barrel with brass fittings on a three-leg pedestal mount.",
    era: "c. late 19th century form",
    origin: "England",
    category: "Vintage Instruments",
    image: img("ae6e01e9-5010-48ed-ab74-6fcc19bc2ac2.webp"),
    imageAlt: "Red and gold decorative telescope on stand",
  },
  {
    id: "hc-gold-orb",
    title: "Engraved Gold Orb",
    description: "Spherical vessel of high-polish gold with floral chasing and pendant drops.",
    era: "Court tradition",
    origin: "Central Asia / Ottoman influence",
    category: "Heritage Objects",
    image: img("08b71fde-bc67-4298-9238-b83f4d45f6bb.webp"),
    imageAlt: "Ornate golden spherical vessel on pedestal",
  },
  {
    id: "hc-crown",
    title: "Openwork Coronet",
    description: "Filigree crown with ruby and sapphire accents — open architecture over leather.",
    era: "Ceremonial form",
    origin: "Europe",
    category: "Rare Memorabilia",
    image: img("08b84ebc-6d73-4933-84cc-98c82bf3f8e1.webp"),
    imageAlt: "Ornate gold crown with red and blue gems",
  },
  {
    id: "hc-crowns-set",
    title: "Triad of Court Crowns",
    description: "Three graduated gilt crowns on velvet — green and ruby stones in baroque settings.",
    era: "Ceremonial suite",
    origin: "Europe",
    category: "Rare Memorabilia",
    image: img("612f0a98-1277-4e7c-8135-ea3cd3877002.webp"),
    imageAlt: "Three gold crowns on red velvet",
  },
  {
    id: "hc-elephant-shield",
    title: "Elephant Crest Shield",
    description: "Heraldic shield with sculpted elephant head, medallions, and botanical painting.",
    era: "Colonial / revival",
    origin: "South Asia / Africa trade",
    category: "Ceremonial Arms",
    image: img("117dac59-19be-4033-93ae-07199c42e043.webp"),
    imageAlt: "Wooden shield with bronze elephant head",
  },
  {
    id: "hc-celtic-shield",
    title: "Celtic Cross Shield",
    description: "Metal heater shield with high-relief Celtic cross and interlace knotwork.",
    era: "Medieval revival",
    origin: "Ireland / Britain",
    category: "Ceremonial Arms",
    image: img("b654889a-67b8-4321-9e36-df6217a6210d.webp"),
    imageAlt: "Bronze shield with Celtic cross design",
  },
  {
    id: "hc-sword",
    title: "Gilt-Inlaid Longsword",
    description: "Polished blade with continuous gold vine inlay and engraved crossguard.",
    era: "Ceremonial form",
    origin: "Europe",
    category: "Ceremonial Arms",
    image: img("91f83229-4499-4fdf-a834-1ca949e576a9.webp"),
    imageAlt: "Ornate sword with gold inlay on wood",
  },
  {
    id: "hc-scabbard",
    title: "Jade-Tone Scabbard",
    description: "Ceremonial scabbard with silver-gilt flora and gold spine — Chinese court idiom.",
    era: "Imperial tradition",
    origin: "China",
    category: "Ceremonial Arms",
    image: img("9c221fa1-1be4-48fc-b571-c2277e34cbd1.webp"),
    imageAlt: "Ornate white and silver ceremonial scabbard",
  },
  {
    id: "hc-strongbox",
    title: "Library Strongbox",
    description: "Mahogany chest with monumental brass lock plate and column corners.",
    era: "c. 18th–19th century form",
    origin: "Europe",
    category: "Decorative Arts",
    image: img("123e9bde-7c3c-4bde-825e-68f78e0636ef.webp"),
    imageAlt: "Ornate wooden strongbox with brass fittings",
  },
  {
    id: "hc-gilt-frame",
    title: "Rococo Picture Frame",
    description: "Empty display frame in heavy gilt with floral crest and ruby accent.",
    era: "c. 18th century form",
    origin: "France / Italy",
    category: "Decorative Arts",
    image: img("4832895e-ede3-4cbe-87c3-4537b5995004.webp"),
    imageAlt: "Empty ornate gold picture frame",
  },
  {
    id: "hc-medallion",
    title: "Allegorical Gold Medallion",
    description: "High-relief gold medal with seated figure, landscape, and mountain horizon.",
    era: "Commemorative",
    origin: "Mint studio",
    category: "Antique Coins",
    image: img("401b3f7b-4147-4cab-804c-7849e99f12f2.webp"),
    imageAlt: "Gold commemorative medallion with female figure",
  },
  {
    id: "hc-crypto-star",
    title: "Star Network Token",
    description: "Commemorative gold token with circuit rim and six-point emblem.",
    era: "Contemporary medal",
    origin: "Digital-era mint",
    category: "Rare Currency",
    image: img("a504e2ff-3c00-49af-a62c-94bfecaba055.webp"),
    imageAlt: "Gold commemorative coin with star emblem",
  },
  {
    id: "hc-crypto-b",
    title: "Circuit Gold Token Pair",
    description: "Twin commemorative pieces with circuit board fields and bold monogram.",
    era: "Contemporary medal",
    origin: "Digital-era mint",
    category: "Rare Currency",
    image: img("b7098d8f-9c6c-4601-9a77-132718ae0023.webp"),
    imageAlt: "Two gold circuit-pattern commemorative coins",
  },
  {
    id: "hc-brass-caddy",
    title: "Bird-Scroll Brass Caddy",
    description: "Cylindrical brass caddy with openwork lid and avian relief on blue enamel ground.",
    era: "Art Nouveau / East Asian fusion",
    origin: "Asia / Europe trade",
    category: "Heritage Objects",
    image: img("57b14942-369a-4c00-9c9f-f4560c8545b6.webp"),
    imageAlt: "Ornate brass cylindrical container with bird relief",
  },
  {
    id: "hc-dallah",
    title: "Engraved Brass Dallah",
    description: "Traditional coffee pot with banded geometric engraving and tall finial lid.",
    era: "c. 19th–20th century",
    origin: "Arabian Peninsula",
    category: "Heritage Objects",
    image: img("b352b8b0-9d67-46d0-b242-8162ef886c2f-684c0b265bbe458ca59bbfd8dd3e97fc.webp"),
    imageAlt: "Traditional engraved brass coffee pot",
  },
  {
    id: "hc-brass-mugs",
    title: "Relief Brass Tankards",
    description: "Paired brass mugs with circular narrative reliefs — market and maritime scenes.",
    era: "Folk metalwork",
    origin: "Middle East / Mediterranean",
    category: "Heritage Objects",
    image: img("c00866ea-5e23-42e6-b2a7-e126cc7594b9-9fdbade92fc04d44b0d1f39d163bf068.webp"),
    imageAlt: "Two engraved brass mugs with scene medallions",
  },
  {
    id: "hc-wicker-glaze",
    title: "Wicker Coil & Glaze Vessel",
    description: "Market still-life of coiled wicker bowl beside a glazed cylindrical vessel.",
    era: "Craft tradition",
    origin: "Regional market",
    category: "Heritage Objects",
    image: img("1b737637-21f3-4552-bb81-a168617dc856.webp"),
    imageAlt: "Wicker coiled bowl and ceramic vessel",
  },
  {
    id: "hc-vintage-car",
    title: "Touring Saloon, Cobblestone",
    description: "Classic multi-window saloon with red wire wheels — urban golden-hour study.",
    era: "c. 1920s–1930s",
    origin: "Europe",
    category: "Rare Memorabilia",
    image: img("56ebdce1-7ff4-4337-bdb0-b5f78109b617.webp"),
    imageAlt: "Vintage dark green classic car on cobblestone street",
  },
  {
    id: "hc-oil-lamp",
    title: "Hurricane Oil Lamp",
    description: "Glass chimney lamp with engraved metal base — warm open flame.",
    era: "c. late 19th century",
    origin: "Middle East / Europe",
    category: "Illumination",
    image: img("b76c8d1b-48c6-4b65-8246-700e9b1cb78e.webp"),
    imageAlt: "Antique oil lamp with glass chimney",
  },
  {
    id: "hc-filigree-lamp",
    title: "Filigree Table Lamp",
    description: "Pierced brass lamp with amber glass shade — lattice light on wood.",
    era: "Ottoman / Maghrebi form",
    origin: "North Africa / Levant",
    category: "Illumination",
    image: img("e7186e52-b9b5-4bcd-9abe-d95ba2792ff9.webp"),
    imageAlt: "Ornate brass filigree lamp with warm light",
  },
  {
    id: "hc-amber-lantern",
    title: "Amber Pedestal Lantern",
    description: "Amber glass body on turned metal stem with filigree collar.",
    era: "Islamic decorative tradition",
    origin: "North Africa / Levant",
    category: "Illumination",
    image: img("e7fd6817-d3d4-4071-b9f5-781a6a3be2ca.webp"),
    imageAlt: "Amber glass lantern lamp on pedestal",
  },
  {
    id: "hc-hanging-lantern",
    title: "Hanging Scroll Lantern",
    description: "Suspended metal lantern with cutwork panels and inner amber glow.",
    era: "Craft tradition",
    origin: "Asia / Middle East",
    category: "Illumination",
    image: img("edbdb192-289f-433b-b444-b43cc7954188.webp"),
    imageAlt: "Hanging ornate metal lantern glowing orange",
  },
  {
    id: "hc-egyptian-pendant",
    title: "Egyptian Revival Pendant",
    description: "Circular gold pendant with pyramids, temple gate, turquoise ring, and gem set.",
    era: "Revival / studio",
    origin: "Egyptian motif",
    category: "Jewelry & Adornment",
    image: img("pendant-egyptian-pyramids.webp"),
    imageAlt: "Gold Egyptian-style pendant with pyramids and gems",
  },
  {
    id: "hc-iridescent-pendant",
    title: "Iridescent Orb Pendant",
    description: "Art Nouveau gold mount holding a liquid-green iridescent sphere.",
    era: "Art Nouveau form",
    origin: "Europe",
    category: "Jewelry & Adornment",
    image: img("pendant-iridescent-trophy.webp"),
    imageAlt: "Gold pendant with iridescent green sphere",
  },
  {
    id: "hc-pyramid-pendant",
    title: "Pyramid Reliquary Pendant",
    description: "Faceted gold pyramid pendant on chain against embossed gold field.",
    era: "Ceremonial form",
    origin: "Studio collection",
    category: "Jewelry & Adornment",
    image: img("5f36791a-7c36-4f0d-8c6e-a155e5ffa847.webp"),
    imageAlt: "Gold pyramid pendant on ornate gold background",
  },
  {
    id: "hc-filigree-locket",
    title: "Filigree Floral Locket",
    description: "Openwork silver-gilt locket with textile flower center and insect motifs.",
    era: "Art Nouveau",
    origin: "Europe",
    category: "Jewelry & Adornment",
    image: img("ab6b3ac4-fb4c-44e3-b300-da42ba6fb891.webp"),
    imageAlt: "Ornate filigree circular pendant with flower center",
  },
  {
    id: "hc-silver-collar",
    title: "Silver Floral Collar",
    description: "Wide multi-strand silver collar with botanical filigree and teardrop pendant.",
    era: "Tribal / atelier fusion",
    origin: "South / Southeast Asia",
    category: "Jewelry & Adornment",
    image: img("8b7dbf8a-03db-4345-b1fb-4e2c99545d14.webp"),
    imageAlt: "Elaborate silver filigree necklace on wood",
  },
  {
    id: "hc-gold-red-collar",
    title: "Gold & Coral Multi-Strand",
    description: "Layered gold collar with red bead strands and floral plaque pendant.",
    era: "Court tradition",
    origin: "South Asia",
    category: "Jewelry & Adornment",
    image: img("c293bf2a-c159-4cdd-8e3d-c95a365a47bf.webp"),
    imageAlt: "Layered gold and red bead necklace on bust",
  },
  {
    id: "hc-peony-necklace",
    title: "Peony Cascade Necklace",
    description: "Gold floral cascade with pearls, turquoise, and hanging medallions.",
    era: "Atelier",
    origin: "East Asia influence",
    category: "Jewelry & Adornment",
    image: img("bfc68ed9-532e-44f5-981e-e45dd3381550.webp"),
    imageAlt: "Gold floral necklace with pearls on red background",
  },
  {
    id: "hc-enamel-collar",
    title: "Polychrome Enamel Collar",
    description: "Dense gold floral collar with enamel petals, bells, and turquoise drop.",
    era: "Court tradition",
    origin: "Central / East Asia",
    category: "Jewelry & Adornment",
    image: img("dbcafd96-5bb0-4479-a59d-7636b0ee73b4.webp"),
    imageAlt: "Elaborate gold and enamel floral necklace",
  },
  {
    id: "hc-amethyst-brooch",
    title: "Amethyst Coronet Brooch",
    description: "Large faceted amethyst in gold starburst with satellite stones.",
    era: "Victorian / revival",
    origin: "Europe",
    category: "Jewelry & Adornment",
    image: img("db46fb99-45d8-4425-bf8e-73b61869aba7.webp"),
    imageAlt: "Gold brooch with large purple amethyst",
  },
  {
    id: "hc-malachite-cuff",
    title: "Malachite Statement Cuff",
    description: "Oval malachite cabochon in brass filigree with mixed crystal accents.",
    era: "Bohemian atelier",
    origin: "Europe",
    category: "Jewelry & Adornment",
    image: img("bcfc9283-f9d3-4fe3-88c6-71fa4b0a30c8.webp"),
    imageAlt: "Ornate cuff with large green malachite stone",
  },
  {
    id: "hc-jewelry-tray",
    title: "Victorian Jewelry Tray",
    description: "Assortment of gold and gem set pieces with pocket watch on velvet board.",
    era: "c. 19th century",
    origin: "Europe",
    category: "Jewelry & Adornment",
    image: img("c56edf31-82cd-4def-90d8-b042c4a1e0cf.webp"),
    imageAlt: "Collection of antique gold jewelry on velvet",
  },
  {
    id: "hc-sunglasses",
    title: "Gilt Round Spectacles",
    description: "Gold-tone round frames with amber gradient lenses under studio light.",
    era: "Mid-century form",
    origin: "Atelier",
    category: "Heritage Objects",
    image: img("bec4c138-1bb6-4985-8a74-bd730838275a-534e79bd80fe42d6b113496ee42fc4e9.webp"),
    imageAlt: "Gold round sunglasses casting shadow",
  },
  {
    id: "hc-handcart",
    title: "Portable Field Handcart",
    description: "Concept handcart with tank and tube fittings — portable medical-era device study.",
    era: "Industrial concept",
    origin: "Workshop collection",
    category: "Heritage Objects",
    image: img("handcart-portable-tank.webp"),
    imageAlt: "Small portable wheeled handcart concept",
  },
]

/** Categories that have at least one catalog item (order follows heritageCategories). */
export function activeHeritageCategories(): string[] {
  const present = new Set(heritageItems.map((i) => i.category))
  return heritageCategories.filter((c) => present.has(c))
}
